services:
  - type: worker
    name: telegram-news-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_KEY
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CATEGORY_URL
        value: https://kun.uz/news/category/texnologiya
      - key: POLL_INTERVAL_SECONDS
        value: "10800"
